import './globals.css';
import 'react-image-gallery/styles/css/image-gallery.css';
import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';
import Footer from '~/components/layouts/Footer';
import Navbar from '~/components/layouts/Navbar';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-josefin',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={josefinSans.className}>
      <body className="antialiased flex flex-col min-h-screen">
        <Navbar />
        <main className="px-4 flex-grow pt-[92px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
